package Display;

import Battle.SkeletonDragon;
import static Display.MapPanel.playerH;
import static Display.MapPanel.playerW;
import static Display.MapPanel.playerX;
import static Display.MapPanel.playerY;
import java.awt.Color;
import Battle.SkeletonMinion;

/**
 *
 * @author 070029319
 */
public class DisplayFrame extends javax.swing.JFrame {

    /**
     * Creates new form Display
     */
    public static int playerHP = 100; //initialize your hp
    public static int mana = 100; //initialize mana
    public static int coins = 50; //number of coins
    public static int potionsHP = 0;//number of hp pots
    public static int potionsM = 0;//number of mana pots
    public static boolean dead = false; //We need this variable to know if we are dead or not

    public DisplayFrame() {
        //Starts MapPanel
        initComponents();
        storePanel1.setVisible(false);
        //By setting Focusable to false this allows the Key bindings to continue to work
        MButton.setFocusable(false);
        HPButton.setFocusable(false);
        skeletonBtn.setFocusable(false);
        bossBtn.setFocusable(false);
        
        //Health bar 
        if (hBar.getValue() == 0 && dead == false){
            hBar.setValue(100);
        }else if (hBar.getValue() == 0 && dead == true){
            dispose(); //Destroy the JFrame object
        }else if (hBar.getValue() > 0 && dead == false) {
            hBar.setValue(SkeletonMinion.currentPlayerHP);
        }
        
        
        //health bar colour changes according to the amount of damage taken
        if (hBar.getValue() <= 100 && hBar.getValue() > 50) {
            hBar.setForeground(Color.green);
        } else if (hBar.getValue() <= 50 && hBar.getValue() > 30) {
            hBar.setForeground(Color.yellow);
        } else if (hBar.getValue() <= 30) {
            hBar.setForeground(Color.red);
        }
        hBar.update(hBar.getGraphics());

        //Mana bar
        mBar.setValue(mana);
        mBar.setForeground(Color.blue);
        mBar.update(hBar.getGraphics());

    }

    //This method is called after every movement to check
    //if the player is in a certain spot
    public static void Locations() {
        //MAP LOCATIONS//
        //Store: This is where you can buy items
        if (playerY + playerH > 580 && playerX < 50) {
            storePanel1.setVisible(true);

        } else if (playerY < 550 || playerX > 30) {

        }
        //Dungeon: This is where you fight enemies
        if (playerY + playerH > 565 && playerX + playerW > 730) {
            mobPanel1.setVisible(true);
        } else if (playerY < 555 || playerX < 720) {
            mobPanel1.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayPanel1 = new Display.MapPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jSpinner1 = new javax.swing.JSpinner();
        jProgressBar2 = new javax.swing.JProgressBar();
        jSeparator1 = new javax.swing.JSeparator();
        displayPanel2 = new Display.MapPanel();
        hBar = new javax.swing.JProgressBar();
        mBar = new javax.swing.JProgressBar();
        storePanel1 = new javax.swing.JPanel();
        HPButton = new javax.swing.JButton();
        MButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        coinLabel = new javax.swing.JLabel();
        MLabel = new javax.swing.JLabel();
        HPLabel = new javax.swing.JLabel();
        mobPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextPane1 = new javax.swing.JTextPane();
        skeletonBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextPane2 = new javax.swing.JTextPane();
        bossBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        displayPanel2.setBackground(new java.awt.Color(102, 102, 102));

        hBar.setBackground(new java.awt.Color(102, 102, 102));
        hBar.setForeground(new java.awt.Color(102, 255, 0));
        hBar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Health", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        mBar.setBackground(new java.awt.Color(102, 102, 102));
        mBar.setForeground(new java.awt.Color(0, 0, 255));
        mBar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mana", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        storePanel1.setBackground(new java.awt.Color(102, 51, 0));
        storePanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        storePanel1.setPreferredSize(new java.awt.Dimension(362, 509));

        HPButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Display/healthPotion.png"))); // NOI18N
        HPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HPButtonActionPerformed(evt);
            }
        });

        MButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Display/manaPotion.png"))); // NOI18N
        MButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Papyrus", 1, 16)); // NOI18N
        jLabel1.setText("Mana Potion");

        jLabel2.setFont(new java.awt.Font("Papyrus", 1, 16)); // NOI18N
        jLabel2.setText("Life Potion");
        jLabel2.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        jLabel3.setText("Store");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Display/coin.gif"))); // NOI18N
        jLabel4.setText("x20");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Display/coin.gif"))); // NOI18N
        jLabel5.setText("x20");

        javax.swing.GroupLayout storePanel1Layout = new javax.swing.GroupLayout(storePanel1);
        storePanel1.setLayout(storePanel1Layout);
        storePanel1Layout.setHorizontalGroup(
            storePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(storePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(storePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(storePanel1Layout.createSequentialGroup()
                        .addComponent(HPButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, storePanel1Layout.createSequentialGroup()
                        .addGroup(storePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(storePanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                        .addGroup(storePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(storePanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(storePanel1Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        storePanel1Layout.setVerticalGroup(
            storePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(storePanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(storePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(HPButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(storePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(storePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addContainerGap(309, Short.MAX_VALUE))
        );

        coinLabel.setForeground(new java.awt.Color(255, 255, 255));
        coinLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Display/coin.gif"))); // NOI18N
        coinLabel.setText("x" + coins);

        MLabel.setForeground(new java.awt.Color(255, 255, 255));
        MLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Display/manaPotion1.png"))); // NOI18N
        MLabel.setText("x" + potionsM);

        HPLabel.setForeground(new java.awt.Color(255, 255, 255));
        HPLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Display/healthPotion1.png"))); // NOI18N
        HPLabel.setText("x" + potionsHP);

        mobPanel1.setBackground(new java.awt.Color(102, 51, 0));
        mobPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Display/skeleton.gif"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        jLabel7.setText("Enemy Arena");

        jTextPane1.setEditable(false);
        jTextPane1.setBackground(new java.awt.Color(102, 51, 0));
        jTextPane1.setFont(new java.awt.Font("Papyrus", 0, 12)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(240, 240, 240));
        jTextPane1.setText("This skeleton is one of the most fearless creatures on the face of the earth. Should you choose to fight it, proceed with caution...");

        skeletonBtn.setBackground(new java.awt.Color(102, 51, 0));
        skeletonBtn.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        skeletonBtn.setForeground(new java.awt.Color(240, 240, 240));
        skeletonBtn.setText("Fight it!");
        skeletonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skeletonBtnActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Battle/boss.gif"))); // NOI18N

        jTextPane2.setEditable(false);
        jTextPane2.setBackground(new java.awt.Color(102, 51, 0));
        jTextPane2.setFont(new java.awt.Font("Papyrus", 0, 12)); // NOI18N
        jTextPane2.setForeground(new java.awt.Color(240, 240, 240));
        jTextPane2.setText("A big scary dragon.");

        bossBtn.setBackground(new java.awt.Color(102, 51, 0));
        bossBtn.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        bossBtn.setForeground(new java.awt.Color(240, 240, 240));
        bossBtn.setText("Fight it!");
        bossBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bossBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mobPanel1Layout = new javax.swing.GroupLayout(mobPanel1);
        mobPanel1.setLayout(mobPanel1Layout);
        mobPanel1Layout.setHorizontalGroup(
            mobPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mobPanel1Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mobPanel1Layout.createSequentialGroup()
                .addGroup(mobPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mobPanel1Layout.createSequentialGroup()
                        .addGroup(mobPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mobPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(bossBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mobPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jTextPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(mobPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(skeletonBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(mobPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(mobPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mobPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addComponent(jLabel8))
                .addGap(42, 42, 42))
        );
        mobPanel1Layout.setVerticalGroup(
            mobPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mobPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mobPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mobPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jTextPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(skeletonBtn))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mobPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mobPanel1Layout.createSequentialGroup()
                        .addComponent(jTextPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bossBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(58, 58, 58))
                    .addGroup(mobPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout displayPanel2Layout = new javax.swing.GroupLayout(displayPanel2);
        displayPanel2.setLayout(displayPanel2Layout);
        displayPanel2Layout.setHorizontalGroup(
            displayPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(displayPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(displayPanel2Layout.createSequentialGroup()
                        .addComponent(hBar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mBar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(HPLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(MLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(coinLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(displayPanel2Layout.createSequentialGroup()
                        .addComponent(mobPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(storePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        displayPanel2Layout.setVerticalGroup(
            displayPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(displayPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mBar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hBar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, displayPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(coinLabel)
                        .addComponent(MLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(HPLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(displayPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mobPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(storePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(172, 172, 172))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(displayPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(displayPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HPButtonActionPerformed
        if (coins >= 20 && potionsHP < 5) {
            potionsHP++;
            coins -= 20;
            HPLabel.setText("x" + potionsHP);
            coinLabel.setText("x" + coins);
        }
    }//GEN-LAST:event_HPButtonActionPerformed

    private void MButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MButtonActionPerformed
        if (coins >= 20 && potionsM < 5) {
            potionsM++;
            coins -= 20;
            MLabel.setText("x" + potionsM);
            coinLabel.setText("x" + coins);
        }
    }//GEN-LAST:event_MButtonActionPerformed

    private void skeletonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skeletonBtnActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SkeletonMinion().setVisible(true);

            }

        }
        );
    }//GEN-LAST:event_skeletonBtnActionPerformed

    private void bossBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bossBtnActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SkeletonDragon().setVisible(true);

            }

        }
        );
    }//GEN-LAST:event_bossBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DisplayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DisplayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DisplayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DisplayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HPButton;
    public static javax.swing.JLabel HPLabel;
    private javax.swing.JButton MButton;
    public static javax.swing.JLabel MLabel;
    private javax.swing.JButton bossBtn;
    public static javax.swing.JLabel coinLabel;
    private Display.MapPanel displayPanel1;
    public static Display.MapPanel displayPanel2;
    public static javax.swing.JProgressBar hBar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    public static javax.swing.JProgressBar mBar;
    public static javax.swing.JPanel mobPanel1;
    private javax.swing.JButton skeletonBtn;
    public static javax.swing.JPanel storePanel1;
    // End of variables declaration//GEN-END:variables
}
